- name: install backup client
  yum:
    name: proxmox-backup
    state: latest
    update_cache: true

- name: copy shell script to remote server
  template:
    src: zaloha.sh.j2
    dest: "{{ backup_script_dest }}"
    mode: '0740'
    owner: root
    group: root

- name: copy variables file to remote server
  template:
    src: backup.conf.j2
    dest: "{{ backup_vars_dest }}"
    mode: '0740'
    owner: root
    group: root

- name: create cronjob to backup every day
  cron:
    name: "proxmox backup"
    minute: "{{ backup_crontab_minute }}"
    hour: "{{ backup_crontab_hour }}"
    job: "{{ backup_script_dest }}"