- name: install backup client
  dnf:
      name: proxmox-backup
      state: latest

- name: create cronjob to backup every day
  cron:
      name: "proxmox backup"
      minute: "{{backup_crontab_minute}}"
      hour: "{{ backup_crontab_hour }}"
      job: "proxmox-backup-client backup backup.pxar:{{backup_path}} --repository {{backup_server_ip}}:{{backup_datastore}}"